const LOCATIONS = [
  { name: "Iyunga", distance: 5, transportFee: 2800 },
  { name: "Mafiati", distance: 3, transportFee: 2600 },
  { name: "Forest", distance: 4, transportFee: 2700 },
  { name: "Airport", distance: 6, transportFee: 2900 },
  { name: "Mbalizi", distance: 12, transportFee: 3500 },
  { name: "Soweto", distance: 2, transportFee: 2500 },
  {
    name: "Mbeya University of Science and Technology (MUST)",
    distance: 7,
    transportFee: 3000,
  },
  { name: "Nane Nane", distance: 6, transportFee: 2900 },
  { name: "Iganjo", distance: 4, transportFee: 2700 },
  { name: "Mwakibete", distance: 5, transportFee: 2800 },
  { name: "Itiji", distance: 4, transportFee: 2700 },
  { name: "Itende", distance: 7, transportFee: 3000 },
  { name: "Mabatini", distance: 3, transportFee: 2600 },
  { name: "Uyole", distance: 9, transportFee: 3200 },
  { name: "Nzovwe", distance: 5, transportFee: 2800 },
  { name: "Ilomba", distance: 6, transportFee: 2900 },
  { name: "TANESCO", distance: 5, transportFee: 2800 },
  { name: "VETA", distance: 8, transportFee: 3100 },
  { name: "Mbeya Hotel", distance: 3, transportFee: 2600 },
  { name: "Ruanda", distance: 4, transportFee: 2700 },
  { name: "Mwanjelwa Market", distance: 0, transportFee: 2300 }, // Since it's the HQ location
  { name: "Isyesye", distance: 6, transportFee: 2900 },
  { name: "Mama John", distance: 7, transportFee: 3000 },
  { name: "Igawilo", distance: 8, transportFee: 3100 },
  { name: "Sinde", distance: 4, transportFee: 2700 },
  { name: "Kadege", distance: 5, transportFee: 2800 },
  { name: "Igurusi", distance: 15, transportFee: 3800 },
  { name: "Ilembo", distance: 20, transportFee: 4300 },
  { name: "Mbalizi Road", distance: 3, transportFee: 2600 },
  { name: "Songwe", distance: 10, transportFee: 3300 },
  { name: "Loleza Peak", distance: 8, transportFee: 3100 },
  { name: "Matalawe", distance: 7, transportFee: 3000 },
  { name: "Umasaini", distance: 4, transportFee: 2700 },
  { name: "Mlowo", distance: 16, transportFee: 3900 },
  { name: "Ipyana", distance: 9, transportFee: 3200 },
  { name: "Ghana", distance: 2, transportFee: 2500 },
  { name: "Ilolo", distance: 7, transportFee: 3000 },
  { name: "Italala", distance: 12, transportFee: 3500 },
  { name: "Ilemi", distance: 5, transportFee: 2800 },
  { name: "Riverside", distance: 3, transportFee: 2600 },
  { name: "Simike", distance: 6, transportFee: 2900 },
  { name: "Gongolamboto", distance: 4, transportFee: 2700 },
  { name: "Itumba", distance: 8, transportFee: 3100 },
  { name: "Mikuyuni", distance: 5, transportFee: 2800 },
  { name: "Songwe Airport", distance: 15, transportFee: 3800 },
  { name: "Kiwira", distance: 10, transportFee: 3300 },
  { name: "Rungwe", distance: 20, transportFee: 4300 },
];

const storageDir = "D:\\gulio-files\\products";

export { LOCATIONS, storageDir };
